name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "*" ]  # This will trigger the workflow on push to any branch
  pull_request:
    branches: [ "*" ]  # This will trigger the workflow on pull requests for any branch

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: mvn --batch-mode --update-snapshots verify

      - run: mkdir staging && cp target/*.jar staging

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
